### ISSUE TITLE
how to develop extension?

### ISSUE THREAD

**Issue by HaveF** [mpppk/chrome-ext-with-cra-ts#16]
hi, mpppk, thanks a lot for this repo,

I know how to use `yarn build` to output the result, and load the extension in chrome, but I don't know how to develop the extension with features like hot reloading etc.

Could you tell me how to develop with this template?

Thanks again :-)

**Comment by mpppk** [comment]
Sorry for delay reply.
I think it is difficult to use `react-script start` for hot reloading while developing chrome extension.
So I have been added new script which `yarn reload`, to reload chrome extension and active tab. Now, when execute `yarn build`, they are automaticaly updated. (See readme and package.json)

However there is a execution-time issue.
On my machine, `react-script build` takes about 5 seconds even with the minimum configuration, because it executes production build by webpack.

To solve the issue, I'm interested in using esbuild which faster bundler instead of webpack. It means we will need to leave from create-react-app,  but I think it's worth considering.

**Comment by HaveF** [comment]
Hi, mpppk, thanks, I'll play with your new stuff later 👍

**Comment by HaveF** [comment]
Wow, it seems you already done with it?
does [mpppk/ts-react-chrome-ext](https://github.com/mpppk/ts-react-chrome-ext) in reasonable stable state?

**Comment by mpppk** [comment]
Oh, you have a quick eye😄  
Yes, the [mpppk/ts-react-chrome-ext](https://github.com/mpppk/ts-react-chrome-ext) is the new boilerplate with shorter build-time powered by esbuild.  
It's just new, so it might have some bugs. I'm developing a simple Chrome extension now, it's ok so far.
